import axios from 'axios'

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'https://backend-three-phi-64.vercel.app/api'

export const api = axios.create({
  baseURL: API_BASE_URL,
  // ── IMPORTANT ──────────────────────────────────────────────────────────────
  // Do NOT set a global Content-Type header here.
  //
  // When sending FormData (file uploads), axios must be free to set
  //   Content-Type: multipart/form-data; boundary=<auto-generated>
  // automatically. If we hard-code 'application/json' here it strips the
  // multipart boundary, multer on the backend receives an empty files array,
  // and ALL image/video uploads silently fail — nothing is saved to Cloudinary
  // and nothing shows up on the site.
  //
  // For JSON requests axios will still send the correct header automatically.
  // ────────────────────────────────────────────────────────────────────────────
})

// Add auth token to requests if available
api.interceptors.request.use((config) => {
  const token = localStorage.getItem('admin_token')
  if (token) {
    config.headers.Authorization = `Bearer ${token}`
  }
  return config
})

// Handle response errors
api.interceptors.response.use(
  (response) => response,
  (error) => {
    if (error.response?.status === 401) {
      const token = localStorage.getItem('admin_token')
      if (token) {
        localStorage.removeItem('admin_token')
        window.location.href = '/admin/login'
      }
    }
    return Promise.reject(error)
  }
)

export default api
